name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  quarto-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: base-meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}

      - name: Build and push quarto base image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/quarto:base
          label: ${{ steps.base-meta.outputs.labels }}
          target: base

            #      - name: Build and push quarto full image
            #        uses: docker/build-push-action@v3
            #        with:
            #          context: .
            #          push: true
            #          tags: ghcr.io/gdolle/quarto:base #${{ steps.base-meta.outputs.tags }}
            #          label: ${{ steps.base-meta.outputs.labels }}
